name: django-product-review-app

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - pip:
      - asgiref
      - certifi
      - chardet
      - defusedxml
      - django==3.1.10
      - django-allauth
      - django-autoslug
      - idna
      - oauthlib
      - python3-openid
      - pytz
      - requests
      - requests-oauthlib
      - sqlparse
      - urllib3