# Generated by Django 3.1.10 on 2022-09-18 01:51

import django.core.validators
from django.db import migrations, models
import django_product_review_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=django_product_review_app.utils.GenerateUniqueName('images/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
